name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: temurin
          overwrite-settings: true
          server-id: opencollab-snapshot-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Setup NMS
        shell: bash
        run: |
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_17_R1
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_18_R1
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_18_R2
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_19_R1
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_19_R2
          mvn ca.bkaw:paper-nms-maven-plugin:1.2.1:init -pl :v1_19_R3
      - name: Deploy with Maven
        run: mvn deploy -B -P deploy
        env:
          MAVEN_USERNAME: ${{ vars.DEPLOY_USER }}
          MAVEN_PASSWORD: ${{ secrets.DEPLOY_PASS }}
